# Generated by Django 2.2.7 on 2020-03-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestedserializers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
    ]
